### ISSUE TITLE
写作魔法树（最小设想）

### ISSUE THREAD

**Issue by lying87** [lying87/Plans-for-BP#9]
为热爱写作，想重拾写作，坚持写作的人栽一颗蓬勃的写作树

最小初心：一边是灵感池，顾名思义，随手快捷收集灵感
                   一边是卡片池，每天坚持140字卡片

灵感池没有功能限制，就像是好用的碎片收集
卡片池里面藏着种子，星卡是种子的能量，点开卡片就锁屏，完成140字后，等于种子种下去了。
离开锁屏，星卡消失，种子没有发芽的能量养分。
种星卡以一周为限，可以用一周的灵感池素材和卡片素材，整理为千字文。这时候种子会发芽。

直到写作树长成，就等于拥有了一本书的量。

发送邀请，开启写作社交——这些都是后续功能，是基于已经有很多人在用产品，而且用户认同这个分享卡片的社交，而后慢慢启动的部分。思路不能颠倒。

**Comment by lying87** [comment]
后面我们发散出去做个社交，其实也可以。但其实最开始的初心只是做一个可以让自己安心写作的东西。输出写作就是目的。后面分享啊链接啊，可能要基于很多人。

@喵星HR  你可以在我们提交问题的页面，把这个页面加上去。我已经发了项目仓库issue。其实这也算是一种产品的思路。开启发送邀请功能，互相可以看卡片、点评，这些都是后面才有的，但是我们关键最小的功能就是为了自己个人坚持输出。

所以我想听一下，阳老师对于我们这种由最小的功能发散开去的，到有社群的，到底有什么想法，我们的BP应该回归到哪一步。

如果保留邀请+社群功能，我们可以再在产品故事后面写。

**Comment by Rina204** [comment]
技术支持来个图片说明
![图片01](http://i4.buimg.com/567571/39a26f2f2118464a.png)
